"""
GEO Implementation Deliverables Generator

Given a GEO audit result, generates a folder of ready-to-use implementation files:
- robots.txt (AI crawler rules)
- llms.txt (LLM permissions)
- organization_schema.json (JSON-LD)
- faqpage_schema.json (JSON-LD template)
- implementation_checklist.md (Korean, prioritized)
- sov_tracking_queries.txt (monthly monitoring)

Usage:
    from geo_deliverables import generate_deliverables
    files = generate_deliverables(audit, "CompanyName", "https://example.com")
"""

import json
import os
import re
import zipfile
from datetime import date
from pathlib import Path

import anthropic
from dotenv import load_dotenv

for _p in [
    Path(__file__).parent / ".env",
    Path(__file__).parent.parent / ".env",
    Path(__file__).parent.parent.parent / ".env",
]:
    if _p.exists():
        load_dotenv(dotenv_path=_p)
        break


def _should_generate(score: int, max_score: int, threshold_pct: float = 0.7) -> bool:
    """Generate artifact if score is below threshold % of max."""
    return score < max_score * threshold_pct


def _generate_robots_txt(website_url: str) -> str:
    """Generate robots.txt with AI crawler Allow rules."""
    sitemap_url = website_url.rstrip("/") + "/sitemap.xml"
    return f"""# robots.txt - AI Crawler Optimized
# Generated by GEO Audit Tool - {date.today().isoformat()}

# Allow all major AI crawlers
User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: CCBot
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: Google-Extended
Allow: /

# Standard crawler rules
User-agent: *
Allow: /
Disallow: /admin/
Disallow: /private/
Disallow: /tmp/

# Sitemap
Sitemap: {sitemap_url}
"""


def _generate_llms_txt(company_name: str, website_url: str) -> str:
    """Generate llms.txt with LLM permissions and guidelines."""
    return f"""# llms.txt - LLM Permissions and Guidelines
# {company_name}
# Generated: {date.today().isoformat()}

# Allow all AI crawlers to use content for responses
Allow: *

# Content usage guidelines
Guidelines:
- All content on this site is permitted for use in AI-generated responses
- Please attribute content to {company_name} when citing
- Do not represent our content as your own analysis
- For permissions questions, visit {website_url}

# Specific content policies
Allow-for-training: /blog /guides /resources /products /services /about
Disallow-for-training: /legal /policies /careers /admin

# Copyright notice
Copyright: {date.today().year} {company_name}. All rights reserved.
"""


def _generate_org_schema(company_name: str, website_url: str, product_category: str = "") -> str:
    """Generate Organization JSON-LD schema."""
    schema = {
        "@context": "https://schema.org",
        "@type": "Organization",
        "name": company_name,
        "url": website_url,
        "logo": f"{website_url.rstrip('/')}/logo.png",
        "description": f"{company_name}" + (f" - {product_category}" if product_category else ""),
        "address": {
            "@type": "PostalAddress",
            "addressCountry": "KR",
            "addressLocality": "[CITY - TODO]",
            "streetAddress": "[ADDRESS - TODO]",
        },
        "contactPoint": {
            "@type": "ContactPoint",
            "contactType": "customer service",
            "telephone": "[PHONE - TODO]",
            "email": "[EMAIL - TODO]",
        },
        "sameAs": [
            "[NAVER_BLOG_URL - TODO]",
            "[INSTAGRAM_URL - TODO]",
            "[KAKAO_CHANNEL_URL - TODO]",
        ],
    }
    return json.dumps(schema, ensure_ascii=False, indent=2)


def _generate_faq_schema(company_name: str, product_category: str) -> str:
    """Generate FAQPage JSON-LD with AI-generated Q&A pairs."""
    # Try to generate relevant FAQ via Claude API
    questions = _generate_faq_questions(company_name, product_category)

    main_entity = []
    for q, a in questions:
        main_entity.append({
            "@type": "Question",
            "name": q,
            "acceptedAnswer": {
                "@type": "Answer",
                "text": a,
            },
        })

    schema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": main_entity,
    }
    return json.dumps(schema, ensure_ascii=False, indent=2)


def _generate_faq_questions(company_name: str, product_category: str) -> list[tuple[str, str]]:
    """Use Claude to generate 3 relevant FAQ Q&A pairs. Falls back to templates."""
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        return _fallback_faq(company_name, product_category)

    try:
        client = anthropic.Anthropic(api_key=api_key)
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            system="Output ONLY valid JSON array. No markdown, no extra text. Keep answers under 80 characters each.",
            messages=[{
                "role": "user",
                "content": (
                    f"Generate 3 FAQ pairs for a Korean company website.\n"
                    f"Company: {company_name}\n"
                    f"Category: {product_category or 'business'}\n\n"
                    f"Output exactly this format:\n"
                    f'[["question1","answer1"],["question2","answer2"],["question3","answer3"]]\n\n'
                    f"Write questions and answers in Korean. Keep each answer under 80 characters."
                ),
            }],
        )
        raw = response.content[0].text.strip()
        if raw.startswith("```"):
            lines = raw.splitlines()
            raw = "\n".join(lines[1:-1]) if lines[-1].strip() == "```" else "\n".join(lines[1:])
        # Attempt to extract valid JSON array even if response is truncated
        # Find first [ and last ] to isolate array
        start = raw.find("[")
        end = raw.rfind("]")
        if start != -1 and end != -1 and end > start:
            raw = raw[start:end + 1]
        pairs = json.loads(raw)
        return [(q, a) for q, a in pairs[:3] if isinstance(q, str) and isinstance(a, str)]
    except Exception as e:
        print(f"[geo_deliverables] FAQ generation error: {e}. Using fallback.")
        return _fallback_faq(company_name, product_category)


def _fallback_faq(company_name: str, product_category: str) -> list[tuple[str, str]]:
    """Template FAQ when API is unavailable."""
    cat = product_category or "services"
    return [
        (
            f"{company_name}은(는) 어떤 회사인가요?",
            f"{company_name}은(는) {cat} 분야에서 활동하는 한국 기업입니다. [TODO: 구체적인 설명을 추가하세요]",
        ),
        (
            f"{company_name}의 주요 제품/서비스는 무엇인가요?",
            f"{company_name}은(는) {cat} 관련 제품과 서비스를 제공합니다. [TODO: 구체적인 제품/서비스 목록을 추가하세요]",
        ),
        (
            f"{company_name}에 문의하려면 어떻게 하나요?",
            f"{company_name} 홈페이지를 통해 문의하실 수 있습니다. [TODO: 연락처 정보를 추가하세요]",
        ),
    ]


def _generate_checklist(breakdown: dict, company_name: str) -> str:
    """Generate Korean implementation checklist, prioritized by score gaps."""
    ai_bot = breakdown.get("ai_bot_access", breakdown.get("crawler_access", 0))
    ai_policy = breakdown.get("ai_policy_file", breakdown.get("llms_txt", 0))
    org_schema = breakdown.get("org_schema", 0)
    content_schema = breakdown.get("content_schema", 0)
    citability = breakdown.get("citability", 0)
    naver = breakdown.get("naver_presence", 0)
    kr_sync = breakdown.get("kr_platform_sync", 0)
    brand_mention = breakdown.get("brand_mention", 0)
    sentiment = breakdown.get("sentiment_quality", 0)

    lines = [
        f"# {company_name} GEO 최적화 구현 체크리스트",
        f"생성일: {date.today().isoformat()}",
        "",
        "---",
        "",
    ]

    # P0 - Blocks AI access
    lines.append("## P0 - AI 접근 차단 해결 (즉시)")
    lines.append("*AI 크롤러가 사이트에 접근할 수 없으면 모든 최적화가 무의미합니다*")
    lines.append("")
    if _should_generate(ai_bot, 20):
        lines.append("- [ ] **robots.txt 업데이트** - GPTBot, ClaudeBot, PerplexityBot 허용 규칙 추가")
        lines.append("  - 파일: `robots.txt` (첨부됨)")
        lines.append("  - 위치: 웹사이트 루트 디렉토리에 업로드")
        lines.append("  - 예상 시간: 5분")
        lines.append("")
    if _should_generate(ai_policy, 10):
        lines.append("- [ ] **llms.txt 생성** - AI 시스템에 콘텐츠 사용 권한 명시")
        lines.append("  - 파일: `llms.txt` (첨부됨)")
        lines.append("  - 위치: 웹사이트 루트 디렉토리에 업로드")
        lines.append("  - 예상 시간: 5분")
        lines.append("")

    # P1 - Quick wins (1 day)
    lines.append("## P1 - 빠른 개선 (1일)")
    lines.append("*즉시 효과를 볼 수 있는 구조화된 데이터 추가*")
    lines.append("")
    if _should_generate(org_schema, 15):
        lines.append("- [ ] **Organization 스키마 추가** - 회사 정보를 AI가 읽을 수 있는 형태로 제공")
        lines.append("  - 파일: `organization_schema.json` (첨부됨)")
        lines.append("  - [TODO] 안의 정보를 실제 데이터로 교체")
        lines.append("  - 홈페이지 `<head>` 태그 안에 `<script type=\"application/ld+json\">` 형태로 삽입")
        lines.append("  - 예상 시간: 30분")
        lines.append("")
    if _should_generate(content_schema, 15):
        lines.append("- [ ] **FAQPage 스키마 추가** - 자주 묻는 질문을 AI가 인용할 수 있는 형태로 구조화")
        lines.append("  - 파일: `faqpage_schema.json` (첨부됨)")
        lines.append("  - Q&A 내용을 실제 비즈니스에 맞게 수정")
        lines.append("  - FAQ 페이지 또는 홈페이지 `<head>` 태그에 삽입")
        lines.append("  - 예상 시간: 1시간")
        lines.append("")
    lines.append("- [ ] **메타 태그 최적화** - title, description에 핵심 키워드 포함")
    lines.append("  - 각 페이지의 `<title>`과 `<meta name=\"description\">`을 구체적으로 작성")
    lines.append("  - 예: '반도체 소재 전문 기업' 대신 '반도체 포토레지스트/식각액 제조 - [회사명]'")
    lines.append("  - 예상 시간: 1-2시간")
    lines.append("")

    # P2 - Medium effort (1 week)
    lines.append("## P2 - 콘텐츠 개선 (1주)")
    lines.append("*AI가 인용할 만한 콘텐츠 구조로 전환*")
    lines.append("")
    if _should_generate(citability, 40, 0.5):
        lines.append("- [ ] **FAQ 섹션 작성** - 고객이 AI에 물어볼 법한 질문 10-15개와 상세 답변")
        lines.append("  - 질문은 자연어 형태: '~는 어떤 회사인가요?', '~의 장점은 무엇인가요?'")
        lines.append("  - 답변은 2-3문장, 구체적 수치/사실 포함")
        lines.append("  - 예상 시간: 3-4시간")
        lines.append("")
    lines.append("- [ ] **회사 소개 페이지 강화** - 300자 이상, 구체적 수치와 실적 포함")
    lines.append("  - 예: '연간 매출 XX억', '직원 XX명', '설립 XXXX년', '주요 고객사: XX, XX'")
    lines.append("  - 예상 시간: 2시간")
    lines.append("")
    if _should_generate(brand_mention, 10):
        lines.append("- [ ] **외부 플랫폼 프로필 업데이트** - 일관된 회사 정보 유지")
        lines.append("  - 네이버 비즈니스 프로필, 카카오맵, 산업 디렉토리")
        lines.append("  - 예상 시간: 2-3시간")
        lines.append("")

    # P3 - Ongoing
    lines.append("## P3 - 지속적 관리 (월간)")
    lines.append("*AI 가시성을 유지하고 개선하기 위한 월간 활동*")
    lines.append("")
    lines.append("- [ ] **월간 SoV(Share of Voice) 추적** - AI가 귀사를 얼마나 추천하는지 모니터링")
    lines.append("  - 파일: `sov_tracking_queries.txt` (첨부됨)")
    lines.append("  - 매월 1회 ChatGPT + Perplexity에서 쿼리 실행")
    lines.append("  - 결과 기록: 날짜, 쿼리, 언급 여부, 경쟁사 언급, 스크린샷")
    lines.append("")
    lines.append("- [ ] **콘텐츠 업데이트** - 분기별 1회 이상 주요 페이지 업데이트")
    lines.append("  - 최신 실적, 신제품, 수상 내역 등 반영")
    lines.append("  - `dateModified` 스키마 속성 업데이트")
    lines.append("")
    lines.append("- [ ] **리뷰/평판 관리** - 고객 리뷰 수집 및 응답")
    lines.append("  - 네이버, 구글, 산업별 플랫폼에서 리뷰 관리")
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*이 체크리스트는 GEO 진단 결과를 기반으로 자동 생성되었습니다.*")
    lines.append(f"*생성 도구: GEO Audit Tool | 생성일: {date.today().isoformat()}*")

    return "\n".join(lines)


def _generate_sov_queries(
    company_name: str,
    product_category: str,
    competitors: list[str] | None = None,
) -> str:
    """Generate SoV tracking queries for monthly monitoring."""
    cat = product_category or "business"
    comp_list = competitors or []

    lines = [
        f"# SoV Tracking Queries - {company_name}",
        f"# Generated: {date.today().isoformat()}",
        "#",
        "# Instructions:",
        "# 1. Run each query in ChatGPT + Perplexity once per month",
        "# 2. Record: date | query | mentioned (Y/N) | competitors mentioned | screenshot",
        "# 3. Calculate SoV = (mentions / total queries) * 100",
        "#",
        "# Korean Queries",
        f"{company_name} 어떤 회사인가요?",
        f"{cat} 추천 회사 한국",
        f"한국 {cat} 업체 추천해주세요",
        f"{cat} 분야 최고 기업은?",
        f"{company_name} 제품 특징",
        f"한국에서 {cat} 잘하는 회사",
        f"{cat} 비교 한국 기업",
        "",
        "# English Queries",
        f"What is {company_name}?",
        f"Best {cat} companies in Korea",
        f"Korean {cat} companies recommended",
        f"{company_name} products and services",
        f"Top {cat} suppliers Korea",
    ]

    if comp_list:
        lines.append("")
        lines.append("# Competitor Comparison Queries")
        for comp in comp_list[:3]:
            lines.append(f"{company_name} vs {comp}")
            lines.append(f"{comp} 대안 추천")

    lines.append("")
    lines.append("# Scoring Template")
    lines.append("# Date | Query | Mentioned | Competitors Mentioned | Notes")
    lines.append(f"# {date.today().isoformat()} | [query] | Y/N | [names] | [notes]")

    return "\n".join(lines)


def generate_deliverables(
    audit: dict,
    company_name: str | None = None,
    website_url: str | None = None,
    product_category: str = "",
    output_dir: str | None = None,
) -> dict:
    """
    Generate implementation deliverables based on GEO audit results.

    Args:
        audit: dict from audit_single_company() or audit_company_geo()
        company_name: override company name (defaults to audit["corp_name"])
        website_url: override website URL (defaults to audit["website_url"])
        product_category: product/service category for FAQ generation
        output_dir: where to save files (defaults to projects/geo-agency/deliverables/)

    Returns:
        dict of {filename: filepath} for all generated artifacts
    """
    corp = company_name or audit.get("corp_name", "Company")
    url = website_url or audit.get("website_url") or "https://example.com"
    breakdown = audit.get("geo_breakdown", {})
    competitors = audit.get("sov_competitors", [])

    if output_dir is None:
        safe_name = re.sub(r'[^\w\-]', '_', corp)
        output_dir = str(Path(__file__).parent / "deliverables" / f"{safe_name}_{date.today().isoformat()}")

    Path(output_dir).mkdir(parents=True, exist_ok=True)
    files = {}

    # A. robots.txt
    ai_bot = breakdown.get("ai_bot_access", breakdown.get("crawler_access", 0))
    if _should_generate(ai_bot, 20):
        path = Path(output_dir) / "robots.txt"
        path.write_text(_generate_robots_txt(url), encoding="utf-8")
        files["robots.txt"] = str(path)
        print(f"[deliverables] Generated: robots.txt")

    # B. llms.txt
    ai_policy = breakdown.get("ai_policy_file", breakdown.get("llms_txt", 0))
    if _should_generate(ai_policy, 10):
        path = Path(output_dir) / "llms.txt"
        path.write_text(_generate_llms_txt(corp, url), encoding="utf-8")
        files["llms.txt"] = str(path)
        print(f"[deliverables] Generated: llms.txt")

    # C. Organization schema
    org_schema = breakdown.get("org_schema", 0)
    if _should_generate(org_schema, 15):
        path = Path(output_dir) / "organization_schema.json"
        path.write_text(_generate_org_schema(corp, url, product_category), encoding="utf-8")
        files["organization_schema.json"] = str(path)
        print(f"[deliverables] Generated: organization_schema.json")

    # D. FAQPage schema
    content_schema = breakdown.get("content_schema", 0)
    if _should_generate(content_schema, 15):
        path = Path(output_dir) / "faqpage_schema.json"
        path.write_text(_generate_faq_schema(corp, product_category), encoding="utf-8")
        files["faqpage_schema.json"] = str(path)
        print(f"[deliverables] Generated: faqpage_schema.json")

    # E. Implementation checklist (always generated)
    path = Path(output_dir) / "implementation_checklist.md"
    path.write_text(_generate_checklist(breakdown, corp), encoding="utf-8")
    files["implementation_checklist.md"] = str(path)
    print(f"[deliverables] Generated: implementation_checklist.md")

    # F. SoV tracking queries (always generated)
    path = Path(output_dir) / "sov_tracking_queries.txt"
    path.write_text(_generate_sov_queries(corp, product_category, competitors), encoding="utf-8")
    files["sov_tracking_queries.txt"] = str(path)
    print(f"[deliverables] Generated: sov_tracking_queries.txt")

    print(f"[deliverables] Total files: {len(files)} in {output_dir}")
    return files


def zip_deliverables(files: dict, zip_path: str | None = None) -> str:
    """Zip all deliverable files into a single archive. Returns zip path."""
    if not files:
        raise ValueError("No deliverable files to zip")

    # Derive zip path from first file's parent directory
    first_path = Path(next(iter(files.values())))
    if zip_path is None:
        zip_path = str(first_path.parent.parent / f"{first_path.parent.name}.zip")

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for filename, filepath in files.items():
            zf.write(filepath, arcname=filename)

    print(f"[deliverables] Zipped: {zip_path}")
    return zip_path


if __name__ == "__main__":
    # Test with a sample audit result
    sample_audit = {
        "corp_name": "TestCorp",
        "geo_score": 35,
        "website_url": "https://testcorp.co.kr",
        "geo_breakdown": {
            "citability": 15,
            "share_of_voice": 2,
            "ai_bot_access": 5,
            "ai_policy_file": 0,
            "org_schema": 3,
            "content_schema": 2,
            "naver_presence": 4,
            "kr_platform_sync": 3,
            "brand_mention": 2,
            "sentiment_quality": 1,
        },
        "sov_competitors": ["CompetitorA", "CompetitorB", "CompetitorC"],
    }

    files = generate_deliverables(
        sample_audit,
        product_category="IT consulting",
        output_dir="deliverables/test_output",
    )

    print(f"\nGenerated {len(files)} files:")
    for name, path in files.items():
        print(f"  {name}: {path}")

    zip_path = zip_deliverables(files)
    print(f"\nZip: {zip_path}")
